completed html-forms
bernardino-www/c0821-code-solutions pull request #7
Opened 2021-08-17 20:04 UTC by bernardino-www

https://user-images.githubusercontent.com/88168364/129792902-ed6e1fcc-932b-4962-a7e5-aba8e71c6d43.mp4

2021-08-17 20:07 UTC, codingcodymiller requested changes
Great start here! A few changes for you:

2021-08-17 20:07 UTC, codingcodymiller commented on html-forms/index.html
> +        <legend>Email:</legend>
This should be the `label` element, not a `legend`

2021-08-17 20:07 UTC, codingcodymiller commented on html-forms/index.html
> +        <legend>Why is coding cool?</legend>
This should be the `label` element, not a `legend`

2021-08-17 20:07 UTC, codingcodymiller commented on html-forms/index.html
> +        <legend>Would you like to sign up for more information?</legend>
This should be the `label` element, not a `legend`

2021-08-17 20:07 UTC, codingcodymiller commented on html-forms/index.html
> +        <legend>Comments:</legend>
This should be the `label` element, not a `legend`

2021-08-17 20:07 UTC, codingcodymiller commented on html-forms/index.html
> +        <label for="submitPrompt"><input type="submit" name="submitPrompt" id="submitPrompt" value="Submit"></label>
There is no text labelling the submit button, so no `label` element is necessary

2021-08-17 20:10 UTC, bernardino-www commented on html-forms/index.html
> +        <label for="submitPrompt"><input type="submit" name="submitPrompt" id="submitPrompt" value="Submit"></label>
Why doesn't the `legend` element suffice compared to the `label` element in this context?

2021-08-17 20:15 UTC, bernardino-www commented on html-forms/index.html
> +        <legend>Email:</legend>
One of the reasons I opted to using `legend` element is that it produces a new line but will make these changes - thanks

2021-08-17 21:34 UTC, codingcodymiller requested changes

2021-08-17 21:34 UTC, codingcodymiller commented on html-forms/index.html
> +        <label for="signUpPrompt">Would you like to sign up for more information?</label>
Almost, the label should actually be around "Sign me up!", this can just be a general text element such as `p`

2021-08-17 21:43 UTC, bernardino-www commented on html-forms/index.html
> +        <label for="signUpPrompt">Would you like to sign up for more information?</label>
May you please expand on this? Can't decipher what you mean - seems ambiguous

2021-08-17 22:41 UTC, codingcodymiller requested changes

2021-08-17 22:41 UTC, codingcodymiller commented on html-forms/index.html
> +        <label for="signUpPrompt">Would you like to sign up for more information?</label>
@bernardino-www No problem! The element you currently have as a `label` should just be a `p` element, And the text "Sign me up!" should be the `label` for this checkbox. You can change the `div` element you have wrapping the element to a `label` like we showed in Q&A, and that should do the trick.

2021-08-17 22:54 UTC, bernardino-www commented on html-forms/index.html
> +        <label for="signUpPrompt">Would you like to sign up for more information?</label>
See new changes based off the most recent commit - thanks

2021-08-17 23:30 UTC, bernardino-www commented on html-forms/index.html
> +        <label for="signUpPrompt">Would you like to sign up for more information?</label>
Not certain if this is based off my most recent commit: does my recent `b886b3b` commit work?

2021-08-18 00:08 UTC, codingcodymiller approved these changes

2021-08-18 00:16 UTC, merged